language: php

php:
  - 7.1.9

services:
  - docker

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

notifications:
  email:
    on_success: never
    on_failure: change

matrix:
  include:
    - env: PHP_VERSION=5.3 WP_VERSION=4.0.23
    - env: PHP_VERSION=5.3 WP_VERSION=latest WP_PULUGIN_DEPLOY=1
    - env: PHP_VERSION=7.2 WP_VERSION=latest
    - env: PHP_VERSION=5.3 WP_VERSION=trunk
    - env: PHP_VERSION=7.2 WP_VERSION=trunk

  allow_failures:
    - env: PHP_VERSION=5.3 WP_VERSION=trunk
    - env: PHP_VERSION=7.2 WP_VERSION=trunk


before_script:
  - composer install
  - curl -L https://raw.githubusercontent.com/miya0001/wpenv/master/run.sh | bash -s $PHP_VERSION $WP_VERSION
  - docker exec -u root wpenv ln -s /home/ubuntu/.phpenv/shims/php /usr/local/bin/
  - docker exec -u root wpenv ln -s /home/ubuntu/.phpenv/shims/composer /usr/local/bin/
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      docker exec wpenv composer global remove "phpunit/phpunit"
      if [[ ${PHP_VERSION:0:2} == "5." ]]; then
        docker exec wpenv composer global require "phpunit/phpunit=4.8.*"
      else
        docker exec wpenv composer global require "phpunit/phpunit=6.*"
      fi
    fi
  - |
  - docker exec -u root wpenv ln -s /home/ubuntu/.phpenv/shims/phpunit /usr/local/bin/

script:
  - docker exec wpenv composer phpcs
  - docker exec wpenv phpunit
  - docker exec -e WP_MULTISITE=1 wpenv phpunit

after_success: curl -L https://raw.githubusercontent.com/miya0001/travis2wpplugin/master/deploy.sh | bash

env:
  global:
    - SVN_REPO: https://plugins.svn.wordpress.org/simple-post-type-permalinks/
    - GH_REF: https://github.com/torounit/simple-post-type-permalinks.git
    - secure: "Q8L8SJFTv+RGTWRaUbhakzCByogcfweBPCYI+wTi6yNHu7tmlRe3yzs6KWuqFB0GhEQlk3t4eNd1XQP14HiK+Y85+XBoeRsm28yGUPK5COMvP3rHG7XyIuzwEqluQQ8NqeEb5W39p6OyEQQ15A/mkbx8CQFIZ1E/lLII68lg3Qc="


